// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1qZrIpc4Ldxi2SnDhcZQy6nneYthGrg',
    appId: '1:331440437004:web:7fe7fa7cc5e340c5e07b29',
    messagingSenderId: '331440437004',
    projectId: 'flutter-chat-app-e3220',
    authDomain: 'flutter-chat-app-e3220.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e3220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5nn4W-MM0uHFmZSt6yVQxvk-6qdHjYU',
    appId: '1:331440437004:android:ac64c46b822863b8e07b29',
    messagingSenderId: '331440437004',
    projectId: 'flutter-chat-app-e3220',
    storageBucket: 'flutter-chat-app-e3220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZyJbIYgpSHoySR2i3Xx10gwC-M-8uC6A',
    appId: '1:331440437004:ios:9c263f793aa56dbbe07b29',
    messagingSenderId: '331440437004',
    projectId: 'flutter-chat-app-e3220',
    storageBucket: 'flutter-chat-app-e3220.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZyJbIYgpSHoySR2i3Xx10gwC-M-8uC6A',
    appId: '1:331440437004:ios:9c263f793aa56dbbe07b29',
    messagingSenderId: '331440437004',
    projectId: 'flutter-chat-app-e3220',
    storageBucket: 'flutter-chat-app-e3220.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW1qZrIpc4Ldxi2SnDhcZQy6nneYthGrg',
    appId: '1:331440437004:web:9df8c50d5ca3a385e07b29',
    messagingSenderId: '331440437004',
    projectId: 'flutter-chat-app-e3220',
    authDomain: 'flutter-chat-app-e3220.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e3220.appspot.com',
  );

}